WITH cohort AS (
  SELECT TICKET_ID, CURRENT_PARTNER_ACCOUNT_ID AS partner_id
  FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (
  SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) AS ts,
         TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR AS ub
  FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID = l.TASK_ID
  WHERE l.EVENT_NAME='TICKET_RESOLVED'
    AND DATE(DATEADD(MINUTE,330, l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'
),
pt AS (
  SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) first_kap_agent,
                  MIN(CASE WHEN ub='1234567890'   THEN ts END) first_csp_app
  FROM ev GROUP BY 1
),
srs AS (
  SELECT TICKET_ID, CSP_ID, WITHIN_TAT, SECONDARY_SUBTYPE, STATUS srs_status,
         CONVERT_TIMEZONE('Asia/Kolkata', SLA_AT)::TIMESTAMP_NTZ      srs_sla,
         CONVERT_TIMEZONE('Asia/Kolkata', RESOLVED_AT)::TIMESTAMP_NTZ srs_resolved,
         CONVERT_TIMEZONE('Asia/Kolkata', INTAKE_TIMESTAMP)::TIMESTAMP_NTZ intake
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY CREATED_AT ASC, VERSION ASC, COMPLAINT_ID ASC)=1
),
ncomp AS (
  SELECT TICKET_ID, COUNT(DISTINCT COMPLAINT_ID) n
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL GROUP BY 1
),
j AS (
  SELECT c.TICKET_ID, s.CSP_ID, s.srs_sla, s.srs_resolved, s.WITHIN_TAT, s.SECONDARY_SUBTYPE,
         COALESCE(n.n,0) n_complaints, p.first_kap_agent, p.first_csp_app,
         CASE WHEN p.first_kap_agent IS NOT NULL AND p.first_csp_app IS NULL THEN 'B_kapture_only'
              WHEN p.first_kap_agent IS NOT NULL AND p.first_csp_app IS NOT NULL
                   AND p.first_kap_agent < p.first_csp_app THEN 'C_kapture_first' END cls
  FROM cohort c
  JOIN pt p ON p.TASK_ID=c.TICKET_ID
  JOIN srs s ON s.TICKET_ID=c.TICKET_ID
  LEFT JOIN ncomp n ON n.TICKET_ID=c.TICKET_ID
  WHERE s.srs_sla IS NOT NULL
)
SELECT cls,
  CASE WHEN n_complaints<=1 THEN 'single_complaint' ELSE 'multi_complaint(reopen)' END scope,
  COUNT(*) tickets, COUNT(DISTINCT CSP_ID) csps,
  SUM(CASE WHEN first_kap_agent <= srs_sla THEN 1 ELSE 0 END)  kap_close_in_tat,
  SUM(CASE WHEN first_csp_app  <= srs_sla THEN 1 ELSE 0 END)   csp_mark_in_tat,
  SUM(CASE WHEN first_kap_agent <= srs_sla AND (first_csp_app > srs_sla OR first_csp_app IS NULL)
           THEN 1 ELSE 0 END) AS SYNC_LOSS_tickets,
  ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY DATEDIFF('second',first_kap_agent,first_csp_app)/3600.0),2) lag_p50_h,
  ROUND(PERCENTILE_CONT(0.9) WITHIN GROUP (ORDER BY DATEDIFF('second',first_kap_agent,first_csp_app)/3600.0),2) lag_p90_h,
  ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY DATEDIFF('second',srs_sla,first_csp_app)/3600.0),2) overshoot_p50_h
FROM j WHERE cls IS NOT NULL
GROUP BY 1,2 ORDER BY 1,2
