WITH cohort AS (
  SELECT TICKET_ID FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, l.EVENT_NAME, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub,
              TRY_PARSE_JSON(l.DATA):Comment::VARCHAR cmt
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME IN ('TICKET_RESOLVED','COMMENT_ADDED')
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN EVENT_NAME='TICKET_RESOLVED' AND ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN EVENT_NAME='TICKET_RESOLVED' AND ub='1234567890'   THEN ts END) fca
       FROM ev GROUP BY 1),
kf AS (SELECT TASK_ID, fka FROM pt WHERE fka IS NOT NULL AND (fca IS NULL OR fka < fca)),
cm AS (
  SELECT k.TASK_ID, k.fka,
         COUNT(CASE WHEN e.EVENT_NAME='COMMENT_ADDED' THEN 1 END) all_comments,
         COUNT(CASE WHEN e.EVENT_NAME='COMMENT_ADDED'
                     AND e.ts BETWEEN DATEADD(MINUTE,-30,k.fka) AND DATEADD(MINUTE,5,k.fka) THEN 1 END) near_close,
         MAX(CASE WHEN e.EVENT_NAME='COMMENT_ADDED'
                   AND e.ts BETWEEN DATEADD(MINUTE,-30,k.fka) AND DATEADD(MINUTE,5,k.fka)
                  THEN LEFT(e.cmt,90) END) cmt_sample
  FROM kf k LEFT JOIN ev e ON e.TASK_ID=k.TASK_ID
  GROUP BY 1,2
)
SELECT COUNT(*) kapture_first_tickets,
       SUM(CASE WHEN near_close>0 THEN 1 ELSE 0 END) with_comment_at_closure,
       ROUND(100.0*SUM(CASE WHEN near_close>0 THEN 1 ELSE 0 END)/COUNT(*),2) pct_with_comment,
       SUM(CASE WHEN all_comments>0 THEN 1 ELSE 0 END) with_any_comment,
       ROUND(100.0*SUM(CASE WHEN all_comments>0 THEN 1 ELSE 0 END)/COUNT(*),2) pct_any
FROM cm
