WITH cohort AS (
  SELECT TICKET_ID FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME='TICKET_RESOLVED'
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca FROM ev GROUP BY 1),
srs AS (
  SELECT TICKET_ID, COMPLAINT_ID, CSP_ID, WITHIN_TAT,
         CONVERT_TIMEZONE('Asia/Kolkata', SLA_AT)::TIMESTAMP_NTZ srs_sla
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY CREATED_AT ASC, VERSION ASC, COMPLAINT_ID ASC)=1
),
led AS (
  SELECT COMPLAINT_ID, RESOLVED_WITHIN_TAT, EXCLUDED_FROM_SCORING, EXCLUSION_REASON,
         STILL_OPEN_AT_48H, OUTCOME, TAT_WINDOW_HOURS
  FROM PROD_DB.CSP_QUALITY_SERVICE_CSP_QUALITY_SERVICE.COMPLAINT_RESOLUTION_LEDGER
  WHERE _FIVETRAN_ACTIVE
  QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPLAINT_ID ORDER BY VERSION DESC)=1
),
j AS (
  SELECT c.TICKET_ID, s.COMPLAINT_ID, s.CSP_ID, s.WITHIN_TAT, s.srs_sla, p.fka, p.fca,
         CASE WHEN p.fka IS NULL THEN 'A_csp_only'
              WHEN p.fca IS NULL THEN 'B_kapture_only'
              WHEN p.fka < p.fca THEN 'C_kapture_first' ELSE 'D_csp_first' END cls,
         CASE WHEN p.fka IS NOT NULL AND p.fka <= s.srs_sla
                   AND (p.fca > s.srs_sla OR p.fca IS NULL) THEN 1 ELSE 0 END sync_loss,
         l.RESOLVED_WITHIN_TAT, l.EXCLUDED_FROM_SCORING, l.EXCLUSION_REASON, l.STILL_OPEN_AT_48H,
         l.OUTCOME, l.COMPLAINT_ID AS in_ledger
  FROM cohort c LEFT JOIN pt p ON p.TASK_ID=c.TICKET_ID
  JOIN srs s ON s.TICKET_ID=c.TICKET_ID
  LEFT JOIN led l ON l.COMPLAINT_ID=s.COMPLAINT_ID
  WHERE s.srs_sla IS NOT NULL
)
SELECT cls, sync_loss,
  COUNT(*) tickets,
  SUM(CASE WHEN in_ledger IS NOT NULL THEN 1 ELSE 0 END) in_quality_ledger,
  SUM(CASE WHEN RESOLVED_WITHIN_TAT = FALSE THEN 1 ELSE 0 END) ledger_breached,
  SUM(CASE WHEN RESOLVED_WITHIN_TAT = TRUE  THEN 1 ELSE 0 END) ledger_within,
  SUM(CASE WHEN EXCLUDED_FROM_SCORING = TRUE THEN 1 ELSE 0 END) excluded,
  SUM(CASE WHEN STILL_OPEN_AT_48H = TRUE THEN 1 ELSE 0 END) still_open_48h,
  MAX(EXCLUSION_REASON) excl_reason, MAX(OUTCOME) outcome_sample
FROM j GROUP BY 1,2 ORDER BY 1,2
