WITH cohort AS (
  SELECT TICKET_ID, DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ) added
  FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-07-01' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME='TICKET_RESOLVED'
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-07-01' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca,
                       COUNT(DISTINCT ub) nub FROM ev GROUP BY 1)
SELECT
  CASE WHEN DAY(c.added) <= 10 THEN TO_CHAR(c.added,'YYYY-MM')||' d01-10'
       ELSE TO_CHAR(c.added,'YYYY-MM')||' d11-EOM' END win,
  COUNT(*) tickets,
  SUM(CASE WHEN p.TASK_ID IS NULL THEN 1 ELSE 0 END) no_resolve_event,
  SUM(CASE WHEN p.fka IS NOT NULL AND (p.fca IS NULL OR p.fka<p.fca) THEN 1 ELSE 0 END) kapture_first,
  ROUND(100.0*SUM(CASE WHEN p.fka IS NOT NULL AND (p.fca IS NULL OR p.fka<p.fca) THEN 1 ELSE 0 END)
        /NULLIF(SUM(CASE WHEN p.TASK_ID IS NOT NULL THEN 1 ELSE 0 END),0),2) pct_of_resolved
FROM cohort c LEFT JOIN pt p ON p.TASK_ID=c.TICKET_ID
GROUP BY 1 ORDER BY 1
