WITH cohort AS (
  SELECT TICKET_ID FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME='TICKET_RESOLVED'
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca FROM ev GROUP BY 1),
srs AS (
  SELECT TICKET_ID, COMPLAINT_ID, CSP_ID, WITHIN_TAT,
         CONVERT_TIMEZONE('Asia/Kolkata', SLA_AT)::TIMESTAMP_NTZ srs_sla
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY CREATED_AT ASC, VERSION ASC, COMPLAINT_ID ASC)=1
),
led AS (SELECT COMPLAINT_ID, RESOLVED_WITHIN_TAT FROM PROD_DB.CSP_QUALITY_SERVICE_CSP_QUALITY_SERVICE.COMPLAINT_RESOLUTION_LEDGER
        WHERE _FIVETRAN_ACTIVE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPLAINT_ID ORDER BY VERSION DESC)=1),
j AS (
  SELECT s.CSP_ID, s.COMPLAINT_ID, l.RESOLVED_WITHIN_TAT,
         CASE WHEN p.fka IS NULL THEN 'A' WHEN p.fca IS NULL THEN 'B'
              WHEN p.fka < p.fca THEN 'C' ELSE 'D' END cls,
         CASE WHEN p.fka IS NOT NULL AND p.fka <= s.srs_sla
                   AND (p.fca > s.srs_sla OR p.fca IS NULL) THEN 1 ELSE 0 END sync_loss
  FROM cohort c LEFT JOIN pt p ON p.TASK_ID=c.TICKET_ID
  JOIN srs s ON s.TICKET_ID=c.TICKET_ID
  LEFT JOIN led l ON l.COMPLAINT_ID=s.COMPLAINT_ID
  WHERE s.srs_sla IS NOT NULL
)
SELECT CSP_ID,
  COUNT(*) scored_tickets,
  SUM(CASE WHEN RESOLVED_WITHIN_TAT=TRUE THEN 1 ELSE 0 END) within_tat,
  SUM(CASE WHEN RESOLVED_WITHIN_TAT=FALSE THEN 1 ELSE 0 END) breached,
  SUM(CASE WHEN cls IN ('B','C') THEN 1 ELSE 0 END) kapture_first_any,
  SUM(sync_loss) sync_loss,
  SUM(CASE WHEN sync_loss=1 AND RESOLVED_WITHIN_TAT=FALSE THEN 1 ELSE 0 END) unfair_breach
FROM j WHERE CSP_ID IS NOT NULL
GROUP BY 1 ORDER BY unfair_breach DESC, scored_tickets DESC
