WITH cohort AS (
  SELECT TICKET_ID FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME='TICKET_RESOLVED'
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca FROM ev GROUP BY 1),
comp AS (
  SELECT TICKET_ID, COUNT(DISTINCT COMPLAINT_ID) n_comp,
         MAX(CASE WHEN IS_REOPEN THEN 1 ELSE 0 END) any_reopen,
         MAX(COALESCE(REOPEN_COUNT,0)) max_reopen_cnt
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL GROUP BY 1
),
rat AS (SELECT RATABLE_ID, AVG(RATING) r, COUNT(*) nr FROM PROD_DB.DYNAMODB_READ.RATING
        WHERE RATABLE_ENTITY='ticket' GROUP BY 1)
SELECT
  CASE WHEN p.fka IS NULL AND p.fca IS NOT NULL THEN 'A_csp_only'
       WHEN p.fka IS NOT NULL AND p.fca IS NULL THEN 'B_kapture_only'
       WHEN p.fka IS NOT NULL AND p.fka<p.fca   THEN 'C_kapture_first'
       WHEN p.fka IS NOT NULL                   THEN 'D_csp_first' ELSE 'E_none' END cls,
  COUNT(*) tickets,
  SUM(COALESCE(cm.any_reopen,0)) tickets_with_reopen,
  ROUND(100.0*SUM(COALESCE(cm.any_reopen,0))/COUNT(*),2) reopen_rate_pct,
  ROUND(AVG(COALESCE(cm.n_comp,0)),3) avg_complaints_per_ticket,
  SUM(CASE WHEN r.RATABLE_ID IS NOT NULL THEN 1 ELSE 0 END) tickets_rated
FROM cohort c LEFT JOIN pt p ON p.TASK_ID=c.TICKET_ID
LEFT JOIN comp cm ON cm.TICKET_ID=c.TICKET_ID
LEFT JOIN rat r ON r.RATABLE_ID::VARCHAR = c.TICKET_ID
GROUP BY 1 ORDER BY 1
