WITH cohort AS (
  SELECT TICKET_ID FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (
  SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
         TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
  FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
  WHERE l.EVENT_NAME='TICKET_RESOLVED'
    AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'
),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca FROM ev GROUP BY 1),
srs AS (
  SELECT TICKET_ID, COMPLAINT_ID, CSP_ID, WITHIN_TAT, STATUS srs_status,
         CONVERT_TIMEZONE('Asia/Kolkata', SLA_AT)::TIMESTAMP_NTZ srs_sla
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY CREATED_AT ASC, VERSION ASC, COMPLAINT_ID ASC)=1
),
tas AS (
  SELECT COMPLAINT_ID, STATE, IS_CSP_ACTIONABLE,
         CONVERT_TIMEZONE('Asia/Kolkata', UPDATED_AT)::TIMESTAMP_NTZ tas_upd
  FROM PROD_DB.CSP_TAS_SERVICE_CSP_TAS_SERVICE.RESTORE_EXECUTION_CANDIDATES
  WHERE _FIVETRAN_ACTIVE AND COMPLAINT_ID IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPLAINT_ID ORDER BY UPDATED_AT DESC, STATE_VERSION DESC)=1
),
j AS (
  SELECT c.TICKET_ID, s.CSP_ID, s.srs_status, s.srs_sla, s.WITHIN_TAT, t.STATE tas_state,
         t.IS_CSP_ACTIONABLE, p.fka, p.fca,
         CASE WHEN p.fka IS NOT NULL AND p.fca IS NULL THEN 'B_kapture_only'
              WHEN p.fka IS NOT NULL AND p.fca IS NOT NULL AND p.fka < p.fca THEN 'C_kapture_first' END cls,
         CASE WHEN p.fka <= s.srs_sla AND (p.fca > s.srs_sla OR p.fca IS NULL) THEN 1 ELSE 0 END sync_loss
  FROM cohort c JOIN pt p ON p.TASK_ID=c.TICKET_ID
  JOIN srs s ON s.TICKET_ID=c.TICKET_ID
  LEFT JOIN tas t ON t.COMPLAINT_ID = s.COMPLAINT_ID
  WHERE s.srs_sla IS NOT NULL
)
SELECT 'TAS state on kapture-closed tickets' hdr, cls, COALESCE(tas_state,'<no candidate>') tas_state,
       COALESCE(IS_CSP_ACTIONABLE::VARCHAR,'-') actionable, COUNT(*) n
FROM j WHERE cls IS NOT NULL GROUP BY 1,2,3,4 ORDER BY 2, n DESC
