WITH cohort AS (
  SELECT TICKET_ID, DATE_TRUNC('month', DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) mth
  FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-03-01' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME='TICKET_RESOLVED'
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-03-01' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca FROM ev GROUP BY 1),
srs AS (
  SELECT TICKET_ID, COMPLAINT_ID, CSP_ID, STATUS srs_status,
         CONVERT_TIMEZONE('Asia/Kolkata', SLA_AT)::TIMESTAMP_NTZ srs_sla
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY CREATED_AT ASC, VERSION ASC, COMPLAINT_ID ASC)=1
),
led AS (SELECT COMPLAINT_ID, RESOLVED_WITHIN_TAT FROM PROD_DB.CSP_QUALITY_SERVICE_CSP_QUALITY_SERVICE.COMPLAINT_RESOLUTION_LEDGER
        WHERE _FIVETRAN_ACTIVE QUALIFY ROW_NUMBER() OVER (PARTITION BY COMPLAINT_ID ORDER BY VERSION DESC)=1)
SELECT c.mth,
  COUNT(*) tickets, COUNT(DISTINCT s.CSP_ID) csps,
  SUM(CASE WHEN p.fka IS NOT NULL AND p.fca IS NULL THEN 1 ELSE 0 END) B_kapture_only,
  SUM(CASE WHEN p.fka IS NOT NULL AND p.fca IS NOT NULL AND p.fka<p.fca THEN 1 ELSE 0 END) C_kapture_first,
  ROUND(100.0*SUM(CASE WHEN p.fka IS NOT NULL AND (p.fca IS NULL OR p.fka<p.fca) THEN 1 ELSE 0 END)/COUNT(*),2) pct_kapture_first,
  SUM(CASE WHEN p.fka IS NOT NULL AND p.fka<=s.srs_sla AND (p.fca>s.srs_sla OR p.fca IS NULL) THEN 1 ELSE 0 END) sync_loss,
  SUM(CASE WHEN p.fka IS NOT NULL AND p.fca IS NULL AND s.srs_status<>'CLOSED' THEN 1 ELSE 0 END) zombie_complaints,
  ROUND(100.0*SUM(CASE WHEN l.RESOLVED_WITHIN_TAT THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN l.RESOLVED_WITHIN_TAT IS NOT NULL THEN 1 ELSE 0 END),0),2) within_tat_pct
FROM cohort c LEFT JOIN pt p ON p.TASK_ID=c.TICKET_ID
JOIN srs s ON s.TICKET_ID=c.TICKET_ID
LEFT JOIN led l ON l.COMPLAINT_ID=s.COMPLAINT_ID
GROUP BY 1 ORDER BY 1
