-- Validate TZ alignment: ticket created (Kapture, NTZ+330) vs complaint created (TZ->IST)
WITH kap AS (
  SELECT TICKET_ID,
         DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ) AS kap_added_ist,
         DATEADD(MINUTE,330, FIRST_RESOLVED_TIME::TIMESTAMP_NTZ) AS kap_res_ist
  FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED = 1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-09-01' AND '2026-09-07'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
srs AS (
  SELECT TICKET_ID,
         MIN(CONVERT_TIMEZONE('Asia/Kolkata', CREATED_AT)::TIMESTAMP_NTZ) AS srs_created_ist
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  GROUP BY 1
)
SELECT
  COUNT(*) matched,
  ROUND(PERCENTILE_CONT(0.05) WITHIN GROUP (ORDER BY DATEDIFF('second', kap_added_ist, srs_created_ist))/60.0,2) p05_min,
  ROUND(PERCENTILE_CONT(0.5)  WITHIN GROUP (ORDER BY DATEDIFF('second', kap_added_ist, srs_created_ist))/60.0,2) p50_min,
  ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY DATEDIFF('second', kap_added_ist, srs_created_ist))/60.0,2) p95_min
FROM kap k JOIN srs s ON s.TICKET_ID = k.TICKET_ID
