WITH cohort AS (
  SELECT TICKET_ID, NO_TIMES_CUSTOMER_CALLED, NO_TIMES_PARTNER_CALLED, TIMES_REOPENED,
         TIMES_REOPENED_POSTCLOSURE, RATING_SCORE_BY_CUSTOMER, TICKET_SOURCE
  FROM PROD_DB.PUBLIC.SERVICE_TICKET_MODEL
  WHERE LAST_TITLE ILIKE 'Internet Issues%' AND IS_PARTNERASSIGNED=1
    AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
    AND DATE(DATEADD(MINUTE,330, TICKET_ADDED_TIME::TIMESTAMP_NTZ)) BETWEEN '2026-08-11' AND '2026-09-10'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY TICKET_ADDED_TIME DESC)=1
),
ev AS (SELECT DISTINCT l.TASK_ID, DATEADD(MINUTE,330,l.ADDED_TIME) ts,
              TRY_PARSE_JSON(l.DATA):updated_by::VARCHAR ub
       FROM PROD_DB.PUBLIC.TICKET_LOGS l JOIN cohort c ON c.TICKET_ID=l.TASK_ID
       WHERE l.EVENT_NAME='TICKET_RESOLVED'
         AND DATE(DATEADD(MINUTE,330,l.ADDED_TIME)) BETWEEN '2026-08-11' AND '2026-09-17'),
pt AS (SELECT TASK_ID, MIN(CASE WHEN ub='137439087976' THEN ts END) fka,
                       MIN(CASE WHEN ub='1234567890'   THEN ts END) fca FROM ev GROUP BY 1),
srs AS (
  SELECT TICKET_ID, COMPLAINT_ID, CSP_ID, STATUS srs_status, ESCALATION_TIER, ESCALATION_COUNT,
         CONVERT_TIMEZONE('Asia/Kolkata', SLA_AT)::TIMESTAMP_NTZ srs_sla,
         CONVERT_TIMEZONE('Asia/Kolkata', CREATED_AT)::TIMESTAMP_NTZ srs_created,
         CONVERT_TIMEZONE('Asia/Kolkata', UPDATED_AT)::TIMESTAMP_NTZ srs_updated,
         BREACH_EMITTED_AT, SIGNAL_EMITTED
  FROM PROD_DB.CSP_SUPPORT_RESOLUTION_SERVICE_CSP_SUPPORT_RESOLUTION_SERVICE.COMPLAINTS
  WHERE _FIVETRAN_ACTIVE AND TICKET_ID IS NOT NULL AND REGEXP_LIKE(TICKET_ID,'^[0-9]+$')
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY CREATED_AT ASC, VERSION ASC, COMPLAINT_ID ASC)=1
),
j AS (
  SELECT c.*, s.srs_status, s.srs_sla, s.srs_created, s.srs_updated, s.SIGNAL_EMITTED,
         s.BREACH_EMITTED_AT, s.ESCALATION_TIER, p.fka, p.fca,
         CASE WHEN p.fka IS NULL AND p.fca IS NOT NULL THEN 'A_csp_only'
              WHEN p.fka IS NOT NULL AND p.fca IS NULL THEN 'B_kapture_only'
              WHEN p.fka IS NOT NULL AND p.fka < p.fca THEN 'C_kapture_first'
              WHEN p.fka IS NOT NULL THEN 'D_csp_first' ELSE 'E_none' END cls
  FROM cohort c LEFT JOIN pt p ON p.TASK_ID=c.TICKET_ID JOIN srs s ON s.TICKET_ID=c.TICKET_ID
)
SELECT cls, COUNT(*) tickets,
  SUM(CASE WHEN srs_status='CLOSED' THEN 1 ELSE 0 END) srs_closed,
  SUM(CASE WHEN srs_status<>'CLOSED' THEN 1 ELSE 0 END) srs_open,
  MAX(srs_status) st_sample,
  ROUND(AVG(CASE WHEN srs_status<>'CLOSED' THEN DATEDIFF('hour', srs_created, CURRENT_TIMESTAMP()) END),0) open_age_hrs_avg,
  SUM(CASE WHEN SIGNAL_EMITTED THEN 1 ELSE 0 END) signal_emitted,
  SUM(CASE WHEN BREACH_EMITTED_AT IS NOT NULL THEN 1 ELSE 0 END) breach_emitted,
  ROUND(AVG(ESCALATION_TIER),2) avg_esc_tier,
  ROUND(AVG(NO_TIMES_CUSTOMER_CALLED),2) cust_calls,
  ROUND(AVG(NO_TIMES_PARTNER_CALLED),2)  partner_calls,
  ROUND(AVG(TIMES_REOPENED_POSTCLOSURE),3) reopen_postclosure,
  SUM(CASE WHEN RATING_SCORE_BY_CUSTOMER IS NOT NULL THEN 1 ELSE 0 END) rated,
  SUM(CASE WHEN TICKET_SOURCE='CUSTOMER_CHAT' THEN 1 ELSE 0 END) from_chat
FROM j GROUP BY 1 ORDER BY 1
